### ISSUE TITLE
Compatibility with Robot Framework 4.0

### ISSUE THREAD

**Issue by Muusssi** [salabs/TestArchiver#39]
Robot Framework 4.0 brings many new features and backwards incompatible changes that need to be tested and checked with both Listener and parser. 

The robot fixture tests need to be updated to include the new features.

RF 4.0 releasenotes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0b1.rst

**Comment by sridharvpmca** [comment]
Hi Team, I have tried testarchiver with RF 4.0b3 and everything works but still get the following warning message "WARNING: begin unknown item 'for'" , "WARNING: begin unknown item 'value'" "WARNING: begin unknown item 'iter '" .. I think it's happening for each test case repeatedly 

Thank you
Sridhar

**Comment by Muusssi** [comment]
Yes, TestArchiver mostly works with RF4.0 but we need to check that everything works with all the new features, schema and api changes. Let's see if we can get that done during the RoboCon week.
