### ISSUE TITLE
WARNING: begin unknown item 'iter' WARNING: begin unknown item 'for' WARNING: begin unknown item 'value'

### ISSUE THREAD

**Issue by nmk1311** [salabs/TestArchiver#49]
For a huge output.xml file, it keeps displaying warning messages and ultimately fails with psycopg2.OperationalError
WARNING: begin unknown item 'iter'
WARNING: begin unknown item 'for'
WARNING: begin unknown item 'value'

psycopg2.OperationalError: server closed the connection unexpectedly 
        This probably means the server terminated abnormally 
        before or while processing the request.

**Comment by Muusssi** [comment]
Those unknown items while parsing the xml hints that you are parsing output generated with RF 4.0 with older version of the tool. Robot Framework 4.0 support was added in 2.4.0 so updating should fix those.

Archiving huge files (i.e. couple GB) should not be an issue IF you can do the parsing close to the database (i.e. low latency in the connection). There is a known issue with the current implementation that means there are a lot of transactions to the database. This means that having a long roundtrip time to the database will cause very long parsing times which then lead to possibly some timeout that breaks the connection. Only thing I can tell from the error is that the db connection was lost during parsing.

**Comment by nmk1311** [comment]
Thanks Muusssi!! You were correct. Updating testarchiver version helped. I have one more issue if anyone is aware.
When we trigger multiple suites from jenkins in same robot command, the testsuite name generated shows the appended name of all testsuites. In my case this name becomes very big for an executive level report. Is there a way to provide an alias name for the job having multiple testsuites?
eg. robot -m testsuite1.robot testsuite2.robot.... testsuite11.robot  . The generated output.xml report on grafana comes with name like testsuite1 testsuite2 testsuite3....testsuite11 which is too big.

**Comment by Muusssi** [comment]
Both in general and especially with TestArchiver, I recommend using other techniques of selecting test suites for your test runs to avoid those long top suite names. Another issue with the technique of just listing the test suites is that the name of the top level suite becomes inconsistent which also affects the full names of test cases. 

I assume that your test suites are all in some folder structure. If you only give the root of the folder structure as the argument for robot, robot will find all the test suites within that folder structure. If you do not want to run all the tests you can use tags and other options to select which tests and suites are executed. (See robot documentation: https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#selecting-test-cases) 

Each folder starting from the given root folder will be represented as a suite containing other suites in robot output. This way the names of suites and especially their full_names (i.e. containing the path of suites starting from the given root suite/folder) are consistent. Consistent test names allows TestArchiver to correctly identify which test cases are actually the same in consecutive executions.
