### ISSUE TITLE
Missing option to archive the complete message log

### ISSUE THREAD

**Issue by RasmusGOlsen** [salabs/TestArchiver#51]
I am missing an option to archive the complete message log, instead of the first 2000 characters. When a test case fails the error information is typically at the end of the log message and not the beginning.

**Comment by Muusssi** [comment]
The limit of 2000 characters was originally a quick fix to handle a limitation in the psycopg2 library on the size of the data. This should be re-evaluated. I have been working with cases where outputs with huge (100s MB) log messages that are usually not worth archiving.
