### ISSUE TITLE
Use TestArchiver by specifying a particular port for a POSGRES database.

### ISSUE THREAD

**Issue by macifTest** [salabs/TestArchiver#55]
I am unable to use TestArchiver by specifying a particular port for a POSGRES database.
Indeed, I have to use a port number which is not the default one, and even specifying it in the command line, it does not pass.
I tried :
- with a config file
- without config file therefore indicating the parameters of the base
- with the listener

Ex : 
testarchiver --config /autom-rbf-tests_POC_Report/resources/technique/db_config.json --dont-require-ssl --port 5691 --team XXX--series jenkins_build_no#Jenkins-Your_Application_Build_No --format robotframework output.xml

testarchiver --dbengine postgresql --database XXX --host XXX --port 5691 --user XXX--password XXX --dont-require-ssl --format robotframework output.xml

robot --listener test_archiver.ArchiverRobotListener:XXX:postgresql:XXX:XXX:XXX:5691 -M Application:POC_TEST_REPORT -i poc_report .

Thanks

**Comment by Muusssi** [comment]
This issue was related to bug that the given database port was taken as config but never used when connecting. This was fixed in PR #50 and the fix released in version 2.5.0
