### ISSUE TITLE
Error messages appear as '0' in log_message table as per v.2.6.0

### ISSUE THREAD

**Issue by bennyvw** [salabs/TestArchiver#61]
As per v.2.6.0 the Robot Framework error messages appear to be zero ('0') in the Archiver database log_message.message field. 
We are using the SQLite database. See attached output.xml (zipped) as an example source and test1.db (zipped) as result db.

Some version information:
Robot Framework 5.0.1
Python 3.10.7
[output.zip](https://github.com/salabs/TestArchiver/files/9764319/output.zip)
[test1.zip](https://github.com/salabs/TestArchiver/files/9764338/test1.zip)

Workaround: downgrading to testarchiver v.2.5.1 resolved the issue for us.

**Comment by Muusssi** [comment]
Thank you for reporting the issue. The log messages are as false values also with postgresql. Iäll look into the issue
