### ISSUE TITLE
Example reports

### ISSUE THREAD

**Issue by jura84** [salabs/TestArchiver#7]
Not directly a bug report, mainly a feature request.

To have:
- output.xml or robot example tescase files with command which can be execute to generate output.xml.
- Example HTML webpages and Flake command

**Detailed description:**
As a user I would like to have an example folder which contains output.xml or robot example tescase files which can be execute to generate output.xml.

With this output.xml file and example HTML file as a user I could with a Flake to open example webpage which visualizes tests executed and saved to DB.

http://flake8.pycqa.org/en/latest/

**Comment by Muusssi** [comment]
The goal is to have fixture fake test sets that can be executed to produce test output for the supported frameworks. These currently exist for 
[Robot Framework](https://github.com/salabs/TestArchiver/tree/master/robot_tests), 
[Mocha junit](https://github.com/salabs/TestArchiver/tree/master/mocha_tests) and 
[pytest junit](https://github.com/salabs/TestArchiver/tree/master/pytest)
For other frameworks any contributions (even simple fixture test set) is appreciated.

For visualising results see [Epimetheus](https://github.com/salabs/Epimetheus). I do not really understand how Flake is related to this.

**Comment by Muusssi** [comment]
I consider this issue closed at this point.
